apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  LOG_LEVEL_ROOT: "INFO"
  # optional: if you want to override server port here instead of Dockerfile
  # SERVER_PORT: "8081"
