apiVersion: v1
kind: Secret
metadata:
  name: driver-secret
type: Opaque
stringData:
  # MySQL on host (use host.docker.internal so pods reach local MySQL)
  SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/driverdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root123"

  # Kafka on host (adjust if your Kafka uses different host/port)
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
